/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import controlador.Controlador_Centros;
import controlador.Detalle;
import java.awt.Image;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.time.Instant;
import java.time.format.DateTimeFormatter;
import java.util.Calendar;
import java.util.Date;
import java.util.GregorianCalendar;
import java.util.Locale;
import java.util.logging.Level;
import java.util.logging.Logger;
import javafx.scene.control.DatePicker;
import javafx.util.converter.LocalDateStringConverter;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import modelo.Alumno;
import modelo.Centro;
import org.jdesktop.swingx.JXDatePicker;

/**
 *
 * @author ferna
 */
public class jpanelDetalle extends javax.swing.JPanel {

    Detalle controlador_detalle;
    Date d;
    boolean bool = true;
    /**
     * Creates new form jpanelDetalle
     */
    public jpanelDetalle(Centro c) throws SQLException {
        initComponents();
        user = c;
        x = new SimpleDateFormat("dd/MM/yyyy");
        controlador_detalle = new Detalle();

       // controlador_detalle.consultadefault(user.getCodigo());
        String srt = "SELECT * FROM ALUMNO WHERE CODIGO_CENTRO = " + user.getCodigo();
        controlador_detalle.ejecutarConsulta(srt);
        //mostarfoto();
        // mostrar();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblcodigo = new javax.swing.JLabel();
        txtcodigo = new javax.swing.JTextField();
        lblnombre = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtnota = new javax.swing.JTextField();
        btnretroceder = new javax.swing.JButton();
        btnavanzar = new javax.swing.JButton();
        datepicker = new org.jdesktop.swingx.JXDatePicker();
        btncambios = new javax.swing.JButton();
        lblfoto = new javax.swing.JLabel();
        btnprimero = new javax.swing.JButton();
        btnultimo = new javax.swing.JButton();

        lblcodigo.setText("Codigo");

        txtcodigo.setEnabled(false);
        txtcodigo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtcodigoActionPerformed(evt);
            }
        });

        lblnombre.setText("Nombre");

        jLabel1.setText("Fecha de nacimiento");

        jLabel2.setText("Nota media");

        btnretroceder.setText("Retroceder");
        btnretroceder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnretrocederActionPerformed(evt);
            }
        });

        btnavanzar.setText("Avanzar");
        btnavanzar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnavanzarActionPerformed(evt);
            }
        });

        datepicker.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                datepickerActionPerformed(evt);
            }
        });

        btncambios.setText("Guardar Cambios");
        btncambios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncambiosActionPerformed(evt);
            }
        });

        lblfoto.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        btnprimero.setText("Ir al primero");
        btnprimero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnprimeroActionPerformed(evt);
            }
        });

        btnultimo.setText("Ir al ultimo");
        btnultimo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnultimoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblnombre)
                            .addComponent(lblcodigo)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2))
                        .addGap(52, 52, 52)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtcodigo)
                            .addComponent(txtNombre)
                            .addComponent(txtnota)
                            .addComponent(datepicker, javax.swing.GroupLayout.DEFAULT_SIZE, 143, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnretroceder)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btncambios)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnavanzar))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnprimero)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnultimo)))
                .addGap(18, 18, 18)
                .addComponent(lblfoto, javax.swing.GroupLayout.DEFAULT_SIZE, 236, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblcodigo)
                            .addComponent(txtcodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblnombre)
                            .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(datepicker, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(20, 20, 20)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(txtnota, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(33, 33, 33)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnretroceder)
                            .addComponent(btnavanzar)
                            .addComponent(btncambios))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnprimero)
                            .addComponent(btnultimo))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(lblfoto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    public void mostarfoto(){
                Controlador_Centros aux = new Controlador_Centros();
                ImageIcon image = new ImageIcon("src/imagenes/"+user.getImagen());
        Icon icon = new ImageIcon(
                image.getImage().getScaledInstance(lblfoto.getWidth(), lblfoto.getHeight(), Image.SCALE_DEFAULT)
        );
        lblfoto.setIcon(icon);
        
        this.repaint();
    }
    
    private void mostrar() throws SQLException {
        if(bool){
            mostarfoto();
            bool=false;
        }
        Alumno a = controlador_detalle.obtenerDatos();
        txtNombre.setText(a.getNombre());
        txtcodigo.setText(""+a.getCodigo());
        txtnota.setText(""+a.getNotaMedia());
        datepicker.setDate(a.getFechaNacimiento().getTime());
        System.out.println(a.getFechaNacimiento());

    }

    private void btnretrocederActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnretrocederActionPerformed
        //JOptionPane.showMessageDialog(this, user.getCodigo());
btnavanzar.setEnabled(true);
        try {
            // Detalle.retroceder();
            controlador_detalle.retroceder();
            mostrar();
        } catch (SQLException ex) {
            Logger.getLogger(jpanelDetalle.class.getName()).log(Level.SEVERE, null, ex);
        }
        try {
            if(controlador_detalle.esPrimero()){
                btnretroceder.setEnabled(false);
            }
        } catch (SQLException ex) {
            Logger.getLogger(jpanelDetalle.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnretrocederActionPerformed

    private void btnavanzarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnavanzarActionPerformed
        btnretroceder.setEnabled(true);
        try {
            //Detalle.avanzar();
            controlador_detalle.avanzar();
            mostrar();
        } catch (SQLException ex) {
            Logger.getLogger(jpanelDetalle.class.getName()).log(Level.SEVERE, null, ex);
        }
                try {
            if(controlador_detalle.esUltimo()){
                btnavanzar.setEnabled(false);
            }
        } catch (SQLException ex) {
            Logger.getLogger(jpanelDetalle.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnavanzarActionPerformed

    private void datepickerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_datepickerActionPerformed
        // TODO add your handling code here:
        d = datepicker.getDate();
        
         
        JOptionPane.showMessageDialog(this, x.format(d));
    }//GEN-LAST:event_datepickerActionPerformed

    private void btncambiosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncambiosActionPerformed
        // TODO add your handling code here:
        //Detalle.guardarRegistro(txtNombre.getText(),x.format(datepicker.getdate()));
        try {
            d=datepicker.getDate();
            
            controlador_detalle.guardarRegistro(txtNombre.getText(),d, Double.parseDouble(txtnota.getText()), Integer.parseInt(txtcodigo.getText()));
          
        } catch (SQLException ex) {
            Logger.getLogger(jpanelDetalle.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btncambiosActionPerformed

    private void txtcodigoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtcodigoActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_txtcodigoActionPerformed

    private void btnprimeroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnprimeroActionPerformed
        try {
            // TODO add your handling code here:
            controlador_detalle.irAlPrincipio();
             mostrar();
             btnretroceder.setEnabled(false);
              btnavanzar.setEnabled(true);
        } catch (SQLException ex) {
            Logger.getLogger(jpanelDetalle.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnprimeroActionPerformed

    private void btnultimoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnultimoActionPerformed
        // TODO add your handling code here:
         try {
            // TODO add your handling code here:
            controlador_detalle.irAlFinal();
            mostrar();
            btnavanzar.setEnabled(false);
            btnretroceder.setEnabled(true);
        } catch (SQLException ex) {
            Logger.getLogger(jpanelDetalle.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnultimoActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnavanzar;
    private javax.swing.JButton btncambios;
    private javax.swing.JButton btnprimero;
    private javax.swing.JButton btnretroceder;
    private javax.swing.JButton btnultimo;
    private org.jdesktop.swingx.JXDatePicker datepicker;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel lblcodigo;
    private javax.swing.JLabel lblfoto;
    private javax.swing.JLabel lblnombre;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtcodigo;
    private javax.swing.JTextField txtnota;
    // End of variables declaration//GEN-END:variables
    Centro user;
    SimpleDateFormat x;
}
