/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import java.awt.Image;
import javax.imageio.ImageIO;
import modelo.Alumno;
import org.jdesktop.swingx.JXImageView;

/**
 *
 * @author ferna
 */
public class jpanelauxiliar extends javax.swing.JPanel {

    /**
     * Creates new form jpanelauxiliar
     */
    public jpanelauxiliar(Alumno alum) {
        initComponents();
        lblnombre.setText(alum.getNombre());
        lblfecha_nacimiento.setText("10/10/10");
        lblcodigo.setText(""+alum.getCodigo());
        lblcodigo_centro.setText(""+alum.getCodigoCentro());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblnombre = new javax.swing.JLabel();
        lblcodigo = new javax.swing.JLabel();
        lblcodigo_centro = new javax.swing.JLabel();
        lblfecha_nacimiento = new javax.swing.JLabel();
        jXImageView1 = new org.jdesktop.swingx.JXImageView();

        lblnombre.setText("Nombre");

        lblcodigo.setText("jLabel2");

        lblcodigo_centro.setText("jLabel3");

        lblfecha_nacimiento.setText("jLabel4");

        javax.swing.GroupLayout jXImageView1Layout = new javax.swing.GroupLayout(jXImageView1);
        jXImageView1.setLayout(jXImageView1Layout);
        jXImageView1Layout.setHorizontalGroup(
            jXImageView1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 165, Short.MAX_VALUE)
        );
        jXImageView1Layout.setVerticalGroup(
            jXImageView1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 181, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblnombre)
                    .addComponent(lblcodigo)
                    .addComponent(lblcodigo_centro)
                    .addComponent(lblfecha_nacimiento))
                .addGap(48, 48, 48)
                .addComponent(jXImageView1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(lblnombre)
                        .addGap(18, 18, 18)
                        .addComponent(lblcodigo)
                        .addGap(18, 18, 18)
                        .addComponent(lblcodigo_centro)
                        .addGap(27, 27, 27)
                        .addComponent(lblfecha_nacimiento))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jXImageView1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private org.jdesktop.swingx.JXImageView jXImageView1;
    private javax.swing.JLabel lblcodigo;
    private javax.swing.JLabel lblcodigo_centro;
    private javax.swing.JLabel lblfecha_nacimiento;
    private javax.swing.JLabel lblnombre;
    // End of variables declaration//GEN-END:variables
}
