/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import controlador.Collection;
import java.awt.Image;
import java.awt.List;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import javax.swing.DefaultListModel;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.ListModel;
import javax.swing.event.ListDataListener;
import modelo.Alumno;
import modelo.Centro;

/**
 *
 * @author ferna
 */
public class jpanellista extends javax.swing.JPanel {

    /**
     * Creates new form jpanellista
     */
    public jpanellista(Centro c) {
        initComponents();
        user=c;
        //listadepaneles();
         
        mostrar();
       
    }
    
    private void mostrar(){
        imagen.setSize(160,160);
        Nombre.setText(user.getNombre());
        password.setText(user.getPassword());
        Codigo.setText(""+user.getCodigo());
        mostarfoto();
        listadepaneles();
    }
    
        public void mostarfoto(){

                ImageIcon image = new ImageIcon("src/imagenes/"+user.getImagen());
        Icon icon = new ImageIcon(
                image.getImage().getScaledInstance(imagen.getWidth(), imagen.getHeight(), Image.SCALE_DEFAULT)
        );
        imagen.setIcon(icon);
        this.repaint();
    }
    private void listadepaneles(){
        ArrayList<Alumno> alum;
        Collection c;
        c = new Collection();
        alum=c.collAlumno(user.getCodigo());
        // DefaultListModel<Alumno> modeloLista = new DefaultListModel<>();
        ArrayList srt = new ArrayList<>();
        DefaultListModel lm = new DefaultListModel();
        // Recorre el array de objetos y añádelos al modelo de lista
        System.out.println(alum.toString());
         x = new SimpleDateFormat("dd/MM/yyyy");
         
        alum.forEach((a) -> {
            Date d = new Date();
            d = a.getFechaNacimiento().getTime();
           
            srt.add("Nombre:"+a.getNombre()
                    +", Fecha de nacimiento:"+x.format(d)
                    +", Nota media:"+a.getNotaMedia());
        });

    // Asigna el modelo de lista al <link>JList</link>
        jlista.setModel(lm);
                for(int i=0;i<srt.size();i++){

            lm.addElement(srt.get(i));
        }
       // jlista.setModel((ListModel<String>) alum);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Nombre = new javax.swing.JLabel();
        Codigo = new javax.swing.JLabel();
        password = new javax.swing.JLabel();
        imagen = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jlista = new javax.swing.JList<>();

        Nombre.setText("jLabel1");

        Codigo.setText("jLabel1");

        password.setText("jLabel1");

        imagen.setBackground(new java.awt.Color(255, 255, 255));
        imagen.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jlista.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane2.setViewportView(jlista);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Nombre)
                    .addComponent(Codigo)
                    .addComponent(password)
                    .addComponent(imagen, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 205, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Codigo)
                .addGap(18, 18, 18)
                .addComponent(Nombre)
                .addGap(18, 18, 18)
                .addComponent(password)
                .addGap(18, 18, 18)
                .addComponent(imagen, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(33, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane2)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Codigo;
    private javax.swing.JLabel Nombre;
    private javax.swing.JLabel imagen;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JList<String> jlista;
    private javax.swing.JLabel password;
    // End of variables declaration//GEN-END:variables
    private Centro user;
    List listapaneles = new List();
    SimpleDateFormat x;
}
